<?php

/**
 * Implements hook_theme().
 */
function custom_google_maps_block_theme($existing, $type, $theme, $path)
{
    return array(
        'maps' => array(
            'variables' => array(
                'width' => NULL,
                'height' => NULL,
                'border' => NULL,
                'border_radius' => NULL,
                'color_border' => NULL,
                'padding_maps' => NULL,
            )
        )
    );
}


function custom_google_maps_block_preprocess_page(&$variables)
{
    $config = \Drupal::config('maps.settings');
    $variables['#attached']['drupalSettings']['maps_key'] = $config->get('maps_key');
}
